

import logging
import os
import os.path
import subprocess

from .. import util

logger = logging.getLogger(__name__)

def OnInit(root):
    os.umask(0o077)  # NOTE: allow 0600
    with util.tempdir() as tmpdir:
        for d in util.get_dict_by_name(root, 'netctl'):
            if d.get('netctl', 'false').lower() == 'true':
                fn      = d.get('name', None)
                ssid    = d.get('SSID', fn)
                pw      = d.get('password', None)
                hidden  = d.get('hidden', 'no')
                if fn and ssid and pw:
                    logger.debug("Writing netctl file %s for: %s", fn, ssid)
                    tmpfile = os.path.join(tmpdir, fn)
                    with open(tmpfile, "w") as f:
                        f.write('# generated by vault\n')
                        f.write("ESSID='%s'\n" % ssid)
                        f.write("Key='%s'\n" % pw)
                        f.write("Hidden=%s\n" % hidden)
                        f.write("Connection=wireless\n")
                        f.write("Security=wpa\n")
                        f.write("IP=dhcp\n")
                        f.write('Interface=$(ls /sys/class/net/ | grep "^w" | head -1)\n')
                    subprocess.check_call(["sudo", "mv", tmpfile, "/etc/netctl/" + fn])
                    subprocess.check_call(["sudo", "chown", "root:root", "/etc/netctl/" + fn])
    return

